listen_addr: ":2222"
host_key_path: "host_key"
authorized_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC85vp8YRG/as/vh3Aoax3D1ObkqwGUKnVWofMdbfeN6 test@example.com"
targets:
  - name: "Web Server"
    host: "10.0.0.1"
    port: "22"
    user: "deploy"
  - name: "Database Server"
    host: "10.0.0.2"
    port: "22"
    user: "admin"
